name: Release

permissions:
  contents: write

on:
  push:
    tags: ['*']

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up Rust
      uses: actions-rs/toolchain@master
      with:
        toolchain: stable

    - name: Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish --all-features

    - name: Create release
      uses: softprops/action-gh-release@master
      with:
        generate_release_notes: true
